### ISSUE TITLE
[URGENT] If you want to know how looks the hacked version

### ISSUE THREAD

**Issue by Hedonismv** [LedgerHQ/connect-kit#33]
![2023-12-14 21 34 19](https://github.com/LedgerHQ/connect-kit/assets/35634423/4b9f31db-313f-4dfe-8c79-14a81eb280f8)

hacked connect upper than original

**Comment by Willzxxz** [comment]
its a modal above the original modal?

**Comment by ComradeAERGO** [comment]
Thanks to everyone for providing feedback.

We just merged version 1.1.8 of the connect-kit-loader that is tethered to version 1.1.8 of the connect-kit.

From here, we'll now deprecate the connect-kit-loader and advise developers to setup connect-kit manually from npm.

Future versions of connect-kit won't be accessible from the loader.
