### ISSUE TITLE
What is the status with WAGMI integration?

### ISSUE THREAD

**Issue by welldan97** [LedgerHQ/connect-kit#53]
Hello dear Ledger team, @Wozacosta,

I have been closely following the updates and am very excited about the upcoming WAGMI integration. I also came across your [PR](https://github.com/wevm/wagmi/pull/3493) on this matter.

However, I am still unclear about its current status. Will it be integrated into WAGMI's official repository, or has Ledger provided any recommendations on how to use it with WAGMI as of now? Could you please provide some clarification on this?

**Comment by Wozacosta** [comment]
Hey @welldan97,

You can still connect to ledger live using wagmi, using the wallet-connect connector as such: 

https://github.com/LedgerHQ/connect-kit/assets/5050709/cfbc590b-ca3d-4f21-911f-95d44f96c9c8

As for a the PR and the potential integration, I'll keep you up to date here once I know more.

**Comment by welldan97** [comment]
Thank you for you reply. That would do it for now. I hope you PR will get merged soon! Good luck! ✨
